### ISSUE TITLE
Missing CNAME file

### ISSUE THREAD

**Issue by darylf** [kpfell/kpfell.github.io#1]
Hey KF,

The description of this repository references [your domain](http://katherinefello.ws/), but GitHub hasn't been told to host that domain. Have you considered [adding your custom domain to a CNAME file](https://help.github.com/articles/setting-up-your-pages-site-repository/#adding-your-custom-domain-to-a-cname-file)?

I realize your description for this repository says "OLD", but thought I'd pass on a heads-up.

Cheers,

Daryl

**Comment by k4y3ff** [comment]
Dude, this repository literally says "OLD" at the top.
